%train Matlab MobileNetv2 on M3 dataset (image classification)

%load('imds_split_Model3.mat');

%manual CNN select/config
%net = mobilenetv2; 
%deepNetworkDesigner %replace classification layer
analyzeNetwork(lgraph_1);

% Resize the images to match the network input layer.
inputSize = [224 224];
imds_training.ReadFcn = @(loc)imresize(imread(loc),inputSize);
imds_val.ReadFcn = @(loc)imresize(imread(loc),inputSize);

%train model
rng(0);

% ------------insert training options----------------
opts = trainingOptions("sgdm",...
    "ExecutionEnvironment","auto",...
    "InitialLearnRate",0.001,...
    "LearnRateDropFactor",0.5,...
    "LearnRateDropPeriod",5,...
    "MaxEpochs",10,...
    "MiniBatchSize",16,...
    "Momentum",0.9,...
    "Shuffle","every-epoch",...
    "Plots","training-progress",...
    "ValidationData",imds_val);
% ------------insert training options----------------

[trainedNet, traininfo] = trainNetwork(imds_training,lgraph_1,opts);